// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.240405.15

#pragma once
#ifndef WINRT_WinUI3_1_H
#define WINRT_WinUI3_1_H
#include "winrt/impl/WinUI3.0.h"
WINRT_EXPORT namespace winrt::WinUI3
{
    struct WINRT_IMPL_EMPTY_BASES IMainWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindow>
    {
        IMainWindow(std::nullptr_t = nullptr) noexcept {}
        IMainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
